# num1 = float(input("enter frist number: "))
# operator = input("enter operator (% * = - + /): ")
# num2 = float (input("enter second number: "))
# if operator == "+" :
#     result = num1 + num2
# elif operator =="-" :
#     result = num1 - num2 
# elif operator == "/":
#     result = num1 / num2
# elif operator =="=" :
#     result = num1 = num2 
# elif operator == "*":
#     result = num1 * num2
# elif operator == "%":
#     result = num1 % num2
#     if num2 != 0:
#         result= num1 / num2

#     else:
#         result ="cannot divide by zero"




# print("Result :",result)


# print (True+ True)
# print(True+ False)


# print ("Bitwise and : 8 ", 5 & 2)

# print("Bitwise or :| ", 5 | 2)

# a = 5
# b = 3

# print(a & b)   
# print(a | b)  
# print(a ^ b)  
# print(~a)      
# print(a << 1)  
# print(a >> 1)  


a = 5
b = 3

print("AND:", a & b)
print("OR:", a | b)
print("XOR:", a ^ b)
print("NOT:", ~a)
print("Left Shift:", a << 1)
print("Right Shift:", a >> 1)

print("AND:", a & b)
print("OR:", a | b)
print("XOR:", a ^ b)
print("NOT:", ~a)
print("Left Shift:", a << 1)
print("Right Shift:", a >> 1)





