# num1 = float(input("enter frist number: "))
# operator = input("enter operator (% * = - + /): ")
# num2 = float (input("enter second number: "))
# if operator == "+" :
#     result = num1 + num2
# elif operator =="-" :
#     result = num1 - num2 
# elif operator == "/":
#     result = num1 / num2
# elif operator =="=" :
#     result = num1 = num2 
# elif operator == "*":
#     result = num1 * num2
# elif operator == "%":
#     result = num1 % num2
#     if num2 != 0:
#         result= num1 / num2

#     else:
#         result ="cannot divide by zero"




# print("Result :",result)


print (True+ True)
print(True+ False)